//
// Created by pytlu on 17.03.2023.
//

#ifndef OBIEKTOWKA_C_MAIN_USTAWIENIA_H
#define OBIEKTOWKA_C_MAIN_USTAWIENIA_H

#endif //OBIEKTOWKA_C_MAIN_USTAWIENIA_H

enum RodzajMieszkanca {GLON,GRZYB,BAKTERIA,PUSTKA,SCIANA,TRUP,NIEZNANE};
enum AkcjaMieszkanca {POTOMEK,POLOWANIE,ROZKALD,NIC};
enum Polozenie{P=0, PG=1, G=2, LG=3, L=4, LD=5, D=6, PD=7, NIGDZIE=8};
